name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: userapi
    
    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [6]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './03.continuous-testing/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ^7.2.2

  deploy:
    
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: " myapp-ece" 
          heroku_email: "bertille.audard@edu.esce.fr"
          appdir: userapi
    
  
